import { addUser, updateUser, deleteUser, getUser } from "./dataStore";
import { UserData } from "./types";

async function testDatabase() {
  try {
    console.log("🚀 Starting database test...");

    // 1️⃣ Add user
    const newUser: UserData = {
        id: -1, // This may be auto-generated by the database
        nameFirst: "John",
        nameLast: "Smith",
        email: "javasmith@gmail.com",
        password: "example123",
        numSuccessfulLogins: 0,
        numFailedPasswordsSinceLastLogin: 0
    };
    newUser.id = await addUser(newUser);
    console.log("➕ User added with id:", newUser.id);

    // 2️⃣ Fetch and log the newly added user
    const fetchedUser = await getUser(newUser.id);
    console.log("🔍 Fetched User:", fetchedUser);

    // 3️⃣ Update the user's details
    const updatedUser: UserData = { ...newUser, nameFirst: "Stacy", nameLast: "Mittens", email: "smitten@gmail.com" };
    const updatedResult = await updateUser(updatedUser);
    console.log("✏️  User updated?", updatedResult);

    // 4️⃣ Fetch and log the updated user
    const fetchedUpdatedUser = await getUser(newUser.id);
    console.log("🔍 Updated User:", fetchedUpdatedUser);

    // 5️⃣ Delete the user
    const deleteResult = await deleteUser(newUser.id);
    console.log("🗑️  User deleted?", deleteResult);

    // 6️⃣ Try fetching deleted user (null)
    const deletedUser = await getUser(newUser.id);
    console.log("🔍 Deleted User (should be null):", deletedUser);

    console.log("✅ Database test completed successfully!");
  } catch (error) {
    console.error("❌ Error during database test:", error);
  }
}

// Run the test function
testDatabase();
